[package]
name = "bort-vk"
version = "0.2.0"
edition = "2021"
license = "MIT"
keywords = ["vulkan", "wrapper", "ash"]
readme = "../README.md"
repository = "https://github.com/lilly-lizard/bort"
homepage = "https://github.com/lilly-lizard/bort"

[dependencies]
# ash is a lightweight vulkan wrapper
ash = "0.37.2"
ash-window = "0.12"
raw-window-handle = "0.5"
# AMD vulkan memory allocator bindings (https://github.com/lilly-lizard/bort-vma)
bort-vma = { version = "0.2.3", path = "../bort-vma" }
